name: Build OpenBLAS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [HASWELL, ARMV8, SKYLAKEX]
        include:
          - os: ubuntu-latest
            ext: so
          - os: macos-latest
            ext: dylib
          - os: windows-latest
            ext: dll

    name: Build OpenBLAS on ${{ matrix.os }} for ${{ matrix.target }}
    steps:
      - name: Checkout OpenBLAS
        uses: actions/checkout@v4
        with:
          repository: OpenMathLib/OpenBLAS
          ref: develop

      - name: Install Dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt install -y make gcc gfortran

      - name: Install Dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install make gcc

      - name: Install Dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        run: choco install make mingw --no-progress

      - name: Build OpenBLAS
        run: |
          make -j$(nproc) TARGET=${{ matrix.target }} DYNAMIC_ARCH=1
        shell: bash
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openblas-${{ matrix.os }}-${{ matrix.target }}
          path: |
            libopenblas.${{ matrix.ext }}
            libopenblas.${{ matrix.ext }}.a
            *.h